### ISSUE TITLE
How to do nothing after 'on_select'

### ISSUE THREAD

**Issue by ShreyBana** [miphreal/python-rofi-menu#7]
I was wondering if it was possible to not exit or refresh the menu in some way after selecting/choosing an item. For some context I am trying to make a volume controller but I have to at-least refresh the menu if I don't want to re run the script every time, so if there is some way to persist the state or refresh the menu and return the highlight to the previously selected item please do let me know.

**Comment by miphreal** [comment]
hey @ShreyBana,

If I understand the issue correctly, you need to show some menu and after selecting one of the menu items you'd like to retain the selection on that menu item. If so, unfortunately, currently rofi (its script mode) does not support controlling which menu item should be pre-selected/highlighted.

---
Some technical details about how Rofi interacts with the script: 
- **on the first run**, it calls the script without any params (tho with some special env variables), 
- then the script generates a menu, outputs it in a special format to the stdout and exits
- rofi captures the output, parses it and shows it as a menu
- **on item selection**, rofi calls the script with the selected menu item as a param and expects the script to either generate a new menu or exit with non-zero status code

For instance, we have a Volume menu with the following items:
- `Volume +`
- `Volume -` 

After selecting any of those items, rofi will call the script, then in the `on_select` method we will handle volume change (e.g. by executing `pactl -- set-sink-volume 1 +10%`) and have to return something to rofi -- a new menu or just exit. The issue is that when we returning a new menu (even if it's the same as the previous one) there's no way to ask rofi to highlight a certain menu item.

**Comment by miphreal** [comment]
Possible solution for the Volume control:

```python
class VolumeControlItem(rofi_menu.ShellItem):
    async def on_select(self, meta):
        await super().on_select(meta)
        await asyncio.sleep(0.1)
        return rofi_menu.Operation(rofi_menu.OP_REFRESH_MENU)


class VolumeControl(rofi_menu.Menu):
    allow_user_input = True
    items = [
        VolumeControlItem(
            "Volume +", "pactl -- set-sink-volume 1 +10%", icon="audio-volume-high"
        ),
        VolumeControlItem(
            "Volume -", "pactl -- set-sink-volume 1 -10%", icon="audio-volume-low"
        ),
    ]

    current_volume_cmd = "pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g'"

    async def pre_render(self, meta):
        proc = await asyncio.create_subprocess_shell(
            self.current_volume_cmd, stdout=asyncio.subprocess.PIPE,
        )
        current_volume = (await proc.stdout.read()).decode().strip()
        self.prompt = f"New volume ({current_volume}%)"

        return await super().pre_render(meta)

    async def on_user_input(self, meta):
        os.system(f"pactl -- set-sink-volume 1 {meta.user_input}%")
        return rofi_menu.Operation(rofi_menu.OP_REFRESH_MENU)


main_menu = rofi_menu.Menu(
    prompt="menu",
    items=[
        rofi_menu.NestedMenu(
            "Volume Control", VolumeControl(), icon="multimedia-volume-control"
        ),
	]
)
```

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/1089024/116445795-efe3ad80-a85e-11eb-9775-1205db455919.gif)

**Comment by ShreyBana** [comment]
There is actually a flag with which you can change the selected row on startup but it only works with dmenu.

**Comment by miphreal** [comment]
_Marking this issue as resolved. Hope the suggested workaround helps._
